# Generated by Django 3.1.3 on 2020-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201214_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=1000),
        ),
    ]
