# Generated by Django 3.1.3 on 2020-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=1000),
        ),
    ]
