# Generated by Django 3.1.3 on 2020-12-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201209_1847'),
        ('home', '0009_auto_20201214_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
    ]
