# Generated by Django 3.1.3 on 2020-12-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201209_1847'),
        ('home', '0010_auto_20201214_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
