# Generated by Django 3.1.3 on 2020-12-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201209_1847'),
        ('home', '0012_auto_20201214_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='100', max_length=200)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('roomtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.roomtype')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
        migrations.DeleteModel(
            name='Suite',
        ),
    ]
