# Generated by Django 3.1.3 on 2020-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201214_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number_of_room',
            field=models.FloatField(),
        ),
    ]
