# Generated by Django 3.1.3 on 2020-12-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201214_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomtype_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
