# Generated by Django 3.1.3 on 2020-12-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_order_room_suite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
        migrations.DeleteModel(
            name='Suite',
        ),
    ]
