# Generated by Django 3.1.3 on 2020-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20201214_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.FloatField(),
        ),
    ]
