# Generated by Django 3.1.3 on 2020-12-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201209_1847'),
        ('home', '0025_auto_20201214_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('roomtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=1, max_digits=90)),
                ('checkin_date', models.DateField(default='12-12-2020')),
                ('checkout_date', models.DateField(default='13-12-2020')),
                ('checkin_key', models.CharField(default='BK2001', max_length=200)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room')),
            ],
        ),
    ]
