# Generated by Django 3.1.3 on 2020-12-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_order_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
