# Generated by Django 3.1.3 on 2020-12-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20201214_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suite',
        ),
    ]
