# Generated by Django 3.1.3 on 2020-12-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_star', models.FloatField()),
                ('address', models.TextField(max_length=100)),
                ('script', models.TextField(max_length=200)),
            ],
        ),
    ]
