# Generated by Django 3.1.3 on 2020-12-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
